### ISSUE TITLE
Problems with ScriptEncoder 

### ISSUE THREAD

**Issue by Jokeyz** [xupefei/BGIKit#3]
Hello,
I tried to convert back txt  Script files into 蒼の彼方のフォーリズム BGi scripts, But the programs stop working 
"MemoryStream is not expanable"
![capture](https://user-images.githubusercontent.com/29946004/27906259-684c8848-6275-11e7-92f8-237f467d2121.PNG)
i don't know if the file size problems or something.
822KB (14047 Lines)

i tried encode 20KB (305 lines) scripts, it seems works.
![image](https://user-images.githubusercontent.com/29946004/27906488-509808ca-6276-11e7-85ff-29b62ce41d89.png)

Please fix it~ ^^

**Comment by xupefei** [comment]
It is a strange exception. Have you modified some code? As I see the Line 164 in Amemiya.Extensions.StreamExtensions.cs is not Write(), but Line 163 is.

**Comment by Jokeyz** [comment]
No, i build the original one.
![image](https://user-images.githubusercontent.com/29946004/27910237-da02d21a-6286-11e7-871c-d8e2b8577434.png)
 
Here, try encode the script. 
[BGIV1-Scripts-Test.zip](https://github.com/xupefei/BGIKit/files/1127751/BGIV1-Scripts-Test.zip)

**Comment by Jokeyz** [comment]
using System;
using System.IO;

namespace Amemiya.Extensions
{
    public static class StreamExtensions
    {
        #region Peek

        public static byte[] PeekBytes(this System.IO.Stream ms, int position, int count)
        {
            long prevPosition = ms.Position;

            ms.Position = position;
            var buffer = ReadBytes(ms, count);
            ms.Position = prevPosition;

            return buffer;
        }

        public static char PeekChar(this System.IO.Stream ms)
        {
            return PeekChar(ms, (int)ms.Position);
        }

        public static char PeekChar(this System.IO.Stream ms, int position)
        {
            return BitConverter.ToChar(PeekBytes(ms, position, 2), 0);
        }

        public static Int16 PeekInt16(this System.IO.Stream ms)
        {
            return PeekInt16(ms, (int)ms.Position);
        }

        public static Int16 PeekInt16(this System.IO.Stream ms, int position)
        {
            return BitConverter.ToInt16(PeekBytes(ms, position, 2), 0);
        }

        public static Int32 PeekInt32(this System.IO.Stream ms)
        {
            return PeekInt32(ms, (int)ms.Position);
        }

        public static Int32 PeekInt32(this System.IO.Stream ms, int position)
        {
            return BitConverter.ToInt32(PeekBytes(ms, position, 4), 0);
        }

        public static Int64 PeekInt64(this System.IO.Stream ms)
        {
            return PeekInt64(ms, (int)ms.Position);
        }

        public static Int64 PeekInt64(this System.IO.Stream ms, int position)
        {
            return BitConverter.ToInt64(PeekBytes(ms, position, 8), 0);
        }

        public static UInt16 PeekUInt16(this System.IO.Stream ms)
        {
            return PeekUInt16(ms, (int)ms.Position);
        }

        public static UInt16 PeekUInt16(this System.IO.Stream ms, int position)
        {
            return BitConverter.ToUInt16(PeekBytes(ms, position, 2), 0);
        }

        public static UInt32 PeekUInt32(this System.IO.Stream ms)
        {
            return PeekUInt32(ms, (int)ms.Position);
        }

        public static UInt32 PeekUInt32(this System.IO.Stream ms, int position)
        {
            return BitConverter.ToUInt32(PeekBytes(ms, position, 4), 0);
        }

        public static UInt64 PeekUInt64(this System.IO.Stream ms)
        {
            return PeekUInt64(ms, (int)ms.Position);
        }

        public static UInt64 PeekUInt64(this System.IO.Stream ms, int position)
        {
            return BitConverter.ToUInt64(PeekBytes(ms, position, 8), 0);
        }

        #endregion Peek

        #region Read

        public static byte[] ReadBytes(this System.IO.Stream ms, int count)
        {
            var buffer = new byte[count];

            if (ms.Read(buffer, 0, count) != count)
                throw new Exception("End reached.");

            return buffer;
        }

        public static char ReadChar(this System.IO.Stream ms)
        {
            return BitConverter.ToChar(ReadBytes(ms, 2), 0);
        }

        public static Int16 ReadInt16(this System.IO.Stream ms)
        {
            return BitConverter.ToInt16(ReadBytes(ms, 2), 0);
        }

        public static Int32 ReadInt32(this System.IO.Stream ms)
        {
            return BitConverter.ToInt32(ReadBytes(ms, 4), 0);
        }

        public static Int64 ReadInt64(this System.IO.Stream ms)
        {
            return BitConverter.ToInt64(ReadBytes(ms, 8), 0);
        }

        public static UInt16 ReadUInt16(this System.IO.Stream ms)
        {
            return BitConverter.ToUInt16(ReadBytes(ms, 2), 0);
        }

        public static UInt32 ReadUInt32(this System.IO.Stream ms)
        {
            return BitConverter.ToUInt32(ReadBytes(ms, 4), 0);
        }

        public static UInt64 ReadUInt64(this System.IO.Stream ms)
        {
            return BitConverter.ToUInt64(ReadBytes(ms, 8), 0);
        }

        #endregion Read

        #region Write

        public static void WriteByte(this System.IO.Stream ms, int position, byte value)
        {
            long prevPosition = ms.Position;

            ms.Position = position;
            ms.WriteByte(value);
            ms.Position = prevPosition;
        }

        public static void WriteBytes(this System.IO.Stream ms, byte[] value)
        {
            ms.Write(value, 0, value.Length);
        }

        public static void WriteBytes(this System.IO.Stream ms, int position, byte[] value)
        {
            long prevPosition = ms.Position;

            ms.Position = position;
            ms.Write(value, 0, value.Length);
            ms.Position = prevPosition;
        }

        public static void WriteInt16(this System.IO.Stream ms, Int16 value)
        {
            ms.Write(BitConverter.GetBytes(value), 0, 2);
        }

        public static void WriteInt16(this System.IO.Stream ms, int position, Int16 value)
        {
            WriteBytes(ms, position, BitConverter.GetBytes(value));
        }

        public static void WriteInt32(this System.IO.Stream ms, Int32 value)
        {
            ms.Write(BitConverter.GetBytes(value), 0, 4);
        }

        public static void WriteInt32(this System.IO.Stream ms, int position, Int32 value)
        {
            WriteBytes(ms, position, BitConverter.GetBytes(value));
        }

        public static void WriteInt64(this System.IO.Stream ms, Int64 value)
        {
            ms.Write(BitConverter.GetBytes(value), 0, 8);
        }

        public static void WriteInt64(this System.IO.Stream ms, int position, Int64 value)
        {
            WriteBytes(ms, position, BitConverter.GetBytes(value));
        }

        public static void WriteUInt16(this System.IO.Stream ms, UInt16 value)
        {
            ms.Write(BitConverter.GetBytes(value), 0, 2);
        }

        public static void WriteUInt16(this System.IO.Stream ms, int position, UInt16 value)
        {
            WriteBytes(ms, position, BitConverter.GetBytes(value));
        }

        public static void WriteUInt32(this System.IO.Stream ms, UInt32 value)
        {
            ms.Write(BitConverter.GetBytes(value), 0, 4);
        }

        public static void WriteUInt32(this System.IO.Stream ms, int position, UInt32 value)
        {
            WriteBytes(ms, position, BitConverter.GetBytes(value));
        }

        public static void WriteUInt64(this System.IO.Stream ms, UInt64 value)
        {
            ms.Write(BitConverter.GetBytes(value), 0, 8);
        }

        public static void WriteUInt64(this System.IO.Stream ms, int position, UInt64 value)
        {
            WriteBytes(ms, position, BitConverter.GetBytes(value));
        }

        #endregion Write
    }
}

**Comment by Jokeyz** [comment]
Encoder files : 
[ScriptEncoder.zip](https://github.com/xupefei/BGIKit/files/1127769/ScriptEncoder.zip)

**Comment by Jokeyz** [comment]
If the files lines too long, n not support. 
try using split options,
-Decoder
Script > UTF-8 Script1.txt Script2.txt Script3.txt.... (Depends file size<file size %3 )>
for example, if BGI-S file size is 900KB. and the max split size is 300KB = 3 .txt files = 900KB
-Encoder
UTF-8 Script1.txt Script2.txt Script3.txt.... + Original Script > Modified Script (Finish)

**Comment by xupefei** [comment]
After a few investigation I found the real problem is already mentioned in https://github.com/xupefei/BGIKit/blob/master/ScriptDecoder/Program.cs#L55.
The script you provided uses 0x01000000 for indicating the offset. So you should change that and decode it again.

PS: I see lots of long duplicate debugging strings in the decoder output. You may use a HashTable (instead of blindly write all strings) in the Encoder to ensure that any duplicate string will only appears once in the Encoder output.

**Comment by Jokeyz** [comment]
thx it works!

btw, the Encoder does not support Unicode? Such as 「」【】?

**Comment by xupefei** [comment]
The Encoder can read Unicode, however, the target codepage you defined [here](https://github.com/xupefei/BGIKit/blob/master/ScriptEncoder/Program.cs#L73) need to have those symbols.

**Comment by Jokeyz** [comment]
what should i replace? CPP 936 > ?

**Comment by xupefei** [comment]
It's depend on you. It should match the OS you want it to run on.
For example, if I translated the game into Chinese, I would expect the translated game runs on a Chinese OS, then I will set the codepage to 936. So for English translation running on a English OS, the codepage should be 1252: https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx

**Comment by Jokeyz** [comment]
Thanks you very much!. then this end of this issue. 
Thanks for your works~ see ya~

**Comment by Cosetto** [comment]
I tried set the encoder to utf-8 but something seems wrong. 
![image](https://user-images.githubusercontent.com/81801486/141037143-c619be8f-2f79-4d59-bcac-0bc3d8ae9e1c.png)
It should looks like this 
![image](https://user-images.githubusercontent.com/81801486/141037200-627a9643-ca33-4142-9176-4882d8cf4645.png)
Does BGI limit character set?

**Comment by xupefei** [comment]
BGI does not support UTF-8.
